# Generated by Django 3.2 on 2022-01-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_auto_20220121_2241'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagvalue',
            unique_together={('tag', 'advertisement')},
        ),
    ]
