# Generated by Django 3.2 on 2022-01-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_tagvalue_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
