# Generated by Django 3.2 on 2022-01-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_alter_advertisement_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='remaining_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='remaining days'),
        ),
    ]
